# Generated by Django 6.0.6 on 2026-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emaildraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='pain_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
