# Generated by Django 6.0.6 on 2026-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_phone_contact_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='behavior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], max_length=10, null=True),
        ),
    ]
