# Generated by Django 6.0.6 on 2026-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact_behavior_contact_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
