# Generated by Django 6.0.6 on 2026-06-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The EmailTask this draft was written under the guidance of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_drafts', to='core.emailtask'),
        ),
    ]
