# Generated by Django 6.0.6 on 2026-06-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
