# Generated by Django 6.0.6 on 2026-06-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_emaildraft_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaildraft',
            name='title',
        ),
    ]
