# Generated by Django 6.0.6 on 2026-06-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_knowledgetag_knowledge_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='tag',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='knowledge', to='core.knowledgetag'),
        ),
    ]
