# Generated by Django 6.0.6 on 2026-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_contact_first_name_alter_contact_last_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emaildraft',
            constraint=models.UniqueConstraint(fields=('contact', 'task', 'version'), name='unique_emaildraft_contact_task_version'),
        ),
    ]
