# Generated by Django 6.0.6 on 2026-06-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_emaildraft_unique_emaildraft_contact_task_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='knowledges',
            field=models.ManyToManyField(blank=True, related_name='email_drafts', to='core.knowledge'),
        ),
    ]
