# Generated by Django 6.0.6 on 2026-06-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_emaildraft_knowledges'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('first_name', 'middle_name', 'last_name', 'email'), name='unique_contact_name_email', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='unique_contact_non_empty_email'),
        ),
    ]
