# Generated by Django 6.0.6 on 2026-06-18 07:54

from collections import defaultdict

from django.db import migrations, models


def _newest_row_key(row):
    return (row["updated_at"], row["created_at"], str(row["id"]))


def _duplicate_groups(rows, key_func):
    groups = defaultdict(list)
    for row in rows:
        groups[key_func(row)].append(row)

    for members in groups.values():
        if len(members) <= 1:
            continue
        members.sort(key=_newest_row_key, reverse=True)
        _keep, *losers = members
        yield losers


def dedupe_contacts(apps, schema_editor):
    Contact = apps.get_model("core", "Contact")
    db_alias = schema_editor.connection.alias
    rows = list(
        Contact.objects.using(db_alias).values(
            "id",
            "first_name",
            "middle_name",
            "last_name",
            "email",
            "created_at",
            "updated_at",
        )
    )

    to_delete = set()

    non_empty_email_rows = [
        row for row in rows if row["email"] is not None and row["email"] != ""
    ]
    for losers in _duplicate_groups(
        non_empty_email_rows,
        key_func=lambda row: row["email"],
    ):
        to_delete.update(row["id"] for row in losers)

    remaining_rows = [row for row in rows if row["id"] not in to_delete]
    for losers in _duplicate_groups(
        remaining_rows,
        key_func=lambda row: (
            row["first_name"],
            row["middle_name"],
            row["last_name"],
            row["email"],
        ),
    ):
        to_delete.update(row["id"] for row in losers)

    if to_delete:
        Contact.objects.using(db_alias).filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_emaildraft_knowledges'),
    ]

    operations = [
        migrations.RunPython(dedupe_contacts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('first_name', 'middle_name', 'last_name', 'email'), name='unique_contact_name_email', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='unique_contact_non_empty_email'),
        ),
    ]
