# Generated by Django 6.0.6 on 2026-06-18 08:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_contact_unique_contact_name_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_contact_non_empty_email',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), name='unique_contact_non_empty_email'),
        ),
    ]
