# Generated by Django 6.0.6 on 2026-06-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_contact_unique_contact_non_empty_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="subscribed",
            field=models.BooleanField(default=True),
        ),
    ]
