# Generated by Django 6.0.6 on 2026-08-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_contacttag_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
